---
- name: Update and install Zsh
  ansible.builtin.apt:
    update_cache: true
    name: zsh
    state: latest
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Check if Oh My Zsh is already installed
  ansible.builtin.stat:
    path: "~/.oh-my-zsh"
  register: ohmyzsh_stat

- name: Install Oh My Zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/bash
  when: not ohmyzsh_stat.stat.exists
  become: true
  become_user: "{{ omz_user }}"

- name: Clone Powerlevel10k theme
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "~/.oh-my-zsh/themes/powerlevel10k"
  become_user: "{{ omz_user }}"

- name: Clone zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  become_user: "{{ omz_user }}"

- name: Clone zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  become_user: "{{ omz_user }}"

- name: Copy .p10k.zsh to home directory
  ansible.builtin.copy:
    src: ../files/.p10k.zsh
    dest: "~/.p10k.zsh"
  become_user: "{{ omz_user }}"

- name: Copy .zshrc to home directory
  ansible.builtin.copy:
    src: ../files/.zshrc
    dest: "~/.zshrc"
  become_user: "{{ omz_user }}"

- name: Change default shell for root user in /etc/passwd
  ansible.builtin.lineinfile:
    path: /etc/passwd
    regexp: "^root:x:0:0:root:/root:/bin/bash"
    line: "root:x:0:0:root:/root:/bin/zsh"
    backrefs: true
  become: true

- name: Change default shell for {{ omz_user }} user in /etc/passwd
  ansible.builtin.lineinfile:
    path: /etc/passwd
    regexp: "^{{ omz_user }}:x:[^:]*:[^:]*:[^:]*:[^:]*:/bin/bash"
    line: "{{ omz_user }}:x:1000:1000::/home/{{ omz_user }}:/bin/zsh"
    backrefs: true
  become: true
  when: omz_user != "root"
...