---
- name: Converge
  hosts: all

  vars:
    user: root

  tasks:

    - name: Install Git on Debian/Ubuntu
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == "Debian"
      become: true

    - name: Install Git on RedHat/CentOS
      ansible.builtin.yum:
        name: git
        state: present
      when: ansible_facts['os_family'] == "RedHat"
      become: true

    - name: "Include chrisurf.oh_my_zsh"
      include_role:
        name: "chrisurf.oh_my_zsh"
...
